### ISSUE TITLE
NoSuchMethodError: 'int com.scurrilous.circe.checksum.Crc32cIntChecksum.computeChecksum

### ISSUE THREAD

**Issue by mbaechler** [CleverCloud/biscuit-pulsar#13]
I'm using this lib alongside pulsar4s 2.6.0 (and pulsar java libs too). My sbt file looks like:
```

      "com.clever-cloud"               % "biscuit-pulsar"            % "1.4.2",
      "com.sksamuel.pulsar4s"          %% "pulsar4s-avro"            % "2.6.0",
      "com.sksamuel.pulsar4s"          %% "pulsar4s-core"            % "2.6.0",
      "com.sksamuel.pulsar4s"          %% "pulsar4s-play-json"       % "2.6.0",
      "com.sksamuel.pulsar4s"          %% "pulsar4s-akka-streams"    % "2.6.0",
      "org.apache.pulsar"              % "pulsar-client-admin"       % "2.6.0",

```
When reading from a topic after using some admin APIs I get this error :

```
java.lang.NoSuchMethodError: 'int com.scurrilous.circe.checksum.Crc32cIntChecksum.computeChecksum(org.apache.pulsar.shade.io.netty.buffer.ByteBuf)'
	at org.apache.pulsar.client.impl.ConsumerImpl.verifyChecksum(ConsumerImpl.java:1256)
	at org.apache.pulsar.client.impl.ConsumerImpl.messageReceived(ConsumerImpl.java:821)
	at org.apache.pulsar.client.impl.ClientCnx.handleMessage(ClientCnx.java:383)
	at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:183)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
	at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at org.apache.pulsar.shade.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1478)
	at org.apache.pulsar.shade.io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1239)
	at org.apache.pulsar.shade.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1276)
	at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:503)
	at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at org.apache.pulsar.shade.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at org.apache.pulsar.shade.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

biscuit plugin pulls pulsar-broken-common with in turn pulls circe-checksum which sadly is duplicated in pulsar-client and pulsar-client-admin but we shaded netty lib, which breaks Crc32cIntChecksum calls

excluding circe-checksum from dependencies solves my issue:

```
("com.clever-cloud"               % "biscuit-pulsar"            % "1.4.2").exclude("org.apache.bookkeeper", "circe-checksum")
```

**Comment by Mefl** [comment]
There is a problem with the packaging, due to the pulsar client jar shading, so you need to exclude the pulsar client to use the non shaded version :

 ```
     "com.sksamuel.pulsar4s" %% "pulsar4s-core" % pulsar4sVersion  exclude("org.apache.pulsar",  "pulsar-client"),
      "com.sksamuel.pulsar4s" %% "pulsar4s-akka-streams" % pulsar4sVersion  exclude("org.apache.pulsar",  "pulsar-client"),
      "com.sksamuel.pulsar4s" %% "pulsar4s-circe" % pulsar4sVersion  exclude("org.apache.pulsar",  "pulsar-client"),
      "com.clever-cloud" % "biscuit-pulsar" % "1.3.0" exclude("org.apache.pulsar",  "pulsar-client")
```

I will add a note into the readme

**Comment by KannarFr** [comment]
@Mefl thx

**Comment by KannarFr** [comment]
@Mefl can you provide this note? Another point (FYI) you can now use AuthenticationToken from pulsar instead of AuthenticationBiscuit. This should make you drop a dependency to biscuit-pulsar.

**Comment by mbaechler** [comment]
@KannarFr can you elaborate ?

**Comment by KannarFr** [comment]
@mbaechler before the latest version, you had to use `com.clevercloud.biscuitpulsar.AuthenticationBiscuit` and add a dependency to `CleverCloud/biscuit-pulsar`. Now you must use pulsar's `org.apache.pulsar.client.impl.auth.AuthenticationToken` and pass either JWT or Biscuit token cf. 859759ac83c505a597434dc0779998f138773143.

With this, biscuit is supported with every pulsar clients via the `AuthenticationToken` provided in these clients.

**Comment by Mefl** [comment]
@KannarFr I did the test : you do not need the dependency at all because using `AuthenticationFactory.create(classOf[AuthenticationToken].getName, biscuitValue)` for the authentification is efficient.
So no more packaging conflict with pulsar4s and we don't need to provide a note explaining the dependency exclusion and the use of `pulsar-client-origin`
